### ISSUE TITLE
Question about Job Format

### ISSUE THREAD

**Issue by pikitgb** [spk/rust-sidekiq#9]
Hi, is there anywhere to use the <at: > key from Job format is not listed or available, i was wondering how i can schedule a job to run at a certain time.

(https://github.com/mperham/sidekiq/wiki/Job-Format)

```
pub struct Job {
    pub class: String,
    pub args: Vec<Value>,
    pub retry: i64,
    pub queue: String,
    pub jid: String,
    pub created_at: u64,
    pub enqueued_at: u64,
}
```

thank you very much !

**Comment by spk** [comment]
Hi, the scheduled Jobs is currently not implemented will try to work on this when I can

**Comment by pikitgb** [comment]
Thanks @spk
